apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: megashop-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: megashop-frontend
            port:
              number: 80


