apiVersion: apps/v1
kind: Deployment
metadata:
  name: megashop-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: megashop-mongo
  template:
    metadata:
      labels:
        app: megashop-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: megashop-mongo
spec:
  selector:
    app: megashop-mongo
  ports:
    - port: 27017
      targetPort: 27017

